### ISSUE TITLE
Theme Fixes

### ISSUE THREAD

**Issue by rodrigopavezi** [SelfKeyFoundation/react-jsonschema-form-material-theme#9]
Theme fix:
- Textarea widget
- Object file widget
- Placeholder
- Link color
- Why URI and EMAIL are upper case? By design?
- Scroll bars in select field
- Check if array fields in playground are rendered correctly (in original playground they are different, is it by. Design?)
- Nested object are not perfect

**Comment by oanamangiurea** [comment]
Obsolete
